### ISSUE TITLE
Folder structure for kitti

### ISSUE THREAD

**Issue by negiabhinit** [yurimjeon1892/EFGH#5]
Can you please share the folder structure required  for kitti odometry?

**Comment by yurimjeon1892** [comment]
The structure is as follows (there may be slight variations).

```
kitti_odom
├── sequences
|   ├── 00
|   |   ├── image_2
|   |   |   ├── 000000.png
|   |   |   └── ...
|   |   ├── velodyne
|   |   |   ├── 000000.bin
|   |   |   └── ...
|   |   └── calib.txt
|   ├── 01
|   └── ...
└── poses
	├── 00.txt
	└── ...
```

**Comment by negiabhinit** [comment]
Can you please upload config files(train and test) for kitti ......
using the folder structure mentioned above still gives errors.

![image](https://github.com/yurimjeon1892/EFGH/assets/38641617/0533d78e-d41b-4e09-94f2-08d2aa14eea5)

**Comment by yurimjeon1892** [comment]
This error seems to be related to the library version. What numba and llvmlite versions are you using? 
I recommend updating the library version by running the following code.

```
pip install numba==0.47.0
pip install llvmlite==0.31.0
```

Or, you can use the upper version via conda.
```
conda install -c numba numba=0.55.0
conda install -c numba llvmlite=0.38.0
```

**Comment by negiabhinit** [comment]
I have exact same installed in my  conda environment
numba==0.47.0
llvmlite==0.31.0

**Comment by negiabhinit** [comment]
and using these
conda install -c numba numba=0.55.0
conda install -c numba llvmlite=0.38.0
gives the following error
![image](https://github.com/yurimjeon1892/EFGH/assets/38641617/2f29eaa9-b2e3-49ef-8f9e-b3a3cdf50ec0)

**Comment by yurimjeon1892** [comment]
Ah, okay. I think numba 0.47.0 and llvmlite 0.31.0 are the correct versions for my code.

What is your ubuntu and cuda version? Have you tested the code with the Rellis-3D dataset? I'm just checking to see if this problem occurs only with the KITTI odometry dataset or also with Rellis.

And here is the config file for kitti (kitti raw). We haven't used the kitti odometry config for a while, so you might need to make a few modifications to the config file below as it's outdated:

```
# general args
test: False
ckpt_dir: ../ckpts/kitti
resume_path: False
pretrained_path: False

arch: EFGH
last_relu: False

use_leaky: True
bcn_use_bias: True
bcn_use_norm: True

DEVICE: cuda

# Dataset
dataset: KITTI
data_root: /data/KITTI_RAW
num_points: 65536
lidar_line: 64
lidar_fov_rad: [0.16666666666, -0.16666666666]
raw_cam_img_size: [352, 1216]

train_samples: -1
val_samples: 500

# for model
dim: 3
batch_size: 1
scale_map: [[1., 1],
            [0.75, 1],
            [0.5, 1],
            [0.25, 1],
            [0.125, 1],
            ]

# miscalleneous
workers: 4


delta_ij_max: 40
translation_max: 10.
accumulation_frame_num: 0
accumulation_frame_skip: 1

convert_dict: {}
grad_false_keys: []

# Train args
lambda:   
  e_gn: 100.
  h_hrzn: 100.
  fov: 100.
  g_trs: 1000.  
  g_depth: 0.1
  g_mask: 1000.
fov_pos_num: 30
fov_neg_ratio: 5

# Train args
weight_decay: 0.0
lr: 0.0001
epochs: 25
iter_iterval: 5000

# Train args
dclb:
  l_rot_range: 0.16666666666
  l_trs_range: 2
  c_rot_range: 0.16666666666
```

**Comment by negiabhinit** [comment]
ubuntu 18.04
Cuda 11.3
I haven't tested on rellis-3D because its a bit difficult to download from baidu(the instructions are in chinese). If you have any other option for downloading kindly let me know.

**Comment by yurimjeon1892** [comment]
When I downloaded the Rellis dataset, it wasn't a Baidu link. It seems to have changed. I don't speak Chinese, so there may be errors, but it looks like you can install the Baidu data download program and download the dataset. 

Anyway, please try using the above configuration file for the KITTI odometry or KITTI raw dataset. If there is an error, please let me know. 

Thank you.

**Comment by negiabhinit** [comment]
I tried still getting the same error.. seems its a numba version associated error
![image](https://github.com/yurimjeon1892/EFGH/assets/38641617/29198738-9010-456f-a483-168abfe11b74)

and for kitti odometry shouldn't we specify kitti sequences for train and test in configuration file

**Comment by yurimjeon1892** [comment]
Okay, I'll try to reproduce this error and address the issue. It may take a few days.

**Comment by negiabhinit** [comment]
Sure , Please!

**Comment by negiabhinit** [comment]
I am getting the same error for RELLIS-3D as well..

**Comment by yurimjeon1892** [comment]
Could you reinstall numpy via
```
pip install numpy==1.19
```
and run again?

**Comment by yurimjeon1892** [comment]
And this is the config file for kitti odometry.

```
# general args
test: False
ckpt_dir: ../ckpts/kitti
resume_path: False
pretrained_path: False

arch: EFGH
last_relu: False

use_leaky: True
bcn_use_bias: True
bcn_use_norm: True

DEVICE: cuda

# Dataset
dataset: KITTI_ODOM
data_root: /data/kitti_odom
num_points: 65536
lidar_line: 64
lidar_fov_rad: [0.16666666666, -0.16666666666]
raw_cam_img_size: [352, 1216]

sequences:
  train: [0]
  valid: [0]

train_samples: -1
val_samples: 500

# for model
dim: 3
batch_size: 1
scale_map: [[1., 1],
            [0.75, 1],
            [0.5, 1],
            [0.25, 1],
            [0.125, 1],
            ]

# miscalleneous
workers: 4

delta_ij_max: 40
translation_max: 10.
accumulation_frame_num: 0
accumulation_frame_skip: 1

convert_dict: {}
grad_false_keys: []

# Train args
lambda:   
  e_gn: 100.
  h_hrzn: 100.
  fov: 100.
  g_trs: 1000.  
  g_depth: 0.1
  g_mask: 1000.
fov_pos_num: 30
fov_neg_ratio: 5

# Train args
weight_decay: 0.0
lr: 0.0001
epochs: 25
iter_iterval: 5000

# Train args
dclb:
  l_rot_range: 0.16666666666
  l_trs_range: 2
  c_rot_range: 0.16666666666
```

Training on both rellis-3d and kitti odometry dataset can be run on my computer with the above settings.
